"""create_postgis_oiltrace_tables

Revision ID: fc8531031167
Revises: 
Create Date: 2026-09-23 16:45:48.025731

"""
from typing import Sequence, Union

from alembic import op
# pyrefly: ignore [missing-import]
import sqlalchemy as sa
# pyrefly: ignore [missing-import]
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fc8531031167'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('spill_id', sa.String(length=128), nullable=False),
    sa.Column('incident_name', sa.String(length=256), nullable=True),
    sa.Column('alert_time', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_scene', sa.String(length=256), nullable=True),
    sa.Column('location_geojson', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=64), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=128), nullable=True),
    sa.Column('acknowledged_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['spill_id'], ['oil_spills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ais_observations', sa.Column('location_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('ais_observations', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('ais_observations', 'mmsi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('ais_observations', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('ais_observations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ais_observations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ais_observations', 'sog_knots',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ais_observations', 'cog_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ais_observations', 'heading_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ais_observations', 'nav_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('ais_observations', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('ais_observations', 'provenance',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('ais_observations', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.drop_index(op.f('idx_ais_mmsi'), table_name='ais_observations')
    op.create_index('idx_ais_observations_location_geom', 'ais_observations', ['location_geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ais_observations_mmsi'), 'ais_observations', ['mmsi'], unique=False)
    op.create_index(op.f('ix_ais_observations_timestamp'), 'ais_observations', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'ais_observations', 'vessels', ['mmsi'], ['mmsi'])
    op.alter_column('analysis_runs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('analysis_runs', 'spill_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'run_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('analysis_runs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('analysis_runs', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('analysis_runs', 'satellite_scene_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'satellite_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'capture_timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'model_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'preprocessing_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'model_threshold',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'environment_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'environment_time_range_start',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'environment_time_range_end',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'windage_coefficient',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'hindcast_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'forecast_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'ais_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'ais_coverage_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'started_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('analysis_runs', 'completed_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'report_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'1.0'"))
    op.alter_column('attributions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('attributions', 'spill_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('attributions', 'mmsi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('attributions', 'distance_km',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'time_delta_h',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'track_overlap_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'heading_compat_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'ais_continuity_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_proximity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_temporal',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_trajectory',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_heading',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_continuity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_proximity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_temporal',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_trajectory',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_heading',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_continuity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'evidence_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'data_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'final_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'ais_gap_duration_min',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'ais_coverage_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'spatial_radius_km',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'temporal_window_h',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('attributions', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('attributions', 'provenance',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('attributions', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_attr_spill'), table_name='attributions')
    op.create_index(op.f('ix_attributions_spill_id'), 'attributions', ['spill_id'], unique=False)
    op.alter_column('audit_log', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('audit_log', 'analysis_run_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('audit_log', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('environmental_fields', 'spill_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'field_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'valid_time_start',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'valid_time_end',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'source_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'resolution_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'provenance',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('investigation_reports', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('investigation_reports', 'spill_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('investigation_reports', 'report_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('investigation_reports', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('investigation_reports', 'report_pdf_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('investigation_reports', 'generated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('investigation_reports', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.add_column('oil_spills', sa.Column('polygon_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('oil_spills', sa.Column('centroid_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('oil_spills', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('oil_spills', 'satellite_image_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('oil_spills', 'incident_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('oil_spills', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('oil_spills', 'detected_class',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('oil_spills', 'detection_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'area_km2',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'perimeter_km',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'length_km',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'width_km',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'orientation_deg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'compactness',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'detection_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('oil_spills', 'satellite_acquisition_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('oil_spills', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('oil_spills', 'provenance',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('oil_spills', 'model_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('oil_spills', 'preprocessing_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('oil_spills', 'model_threshold',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'region_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('oil_spills', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('oil_spills', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('oil_spills', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index('idx_oil_spills_centroid_geom', 'oil_spills', ['centroid_geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_oil_spills_polygon_geom', 'oil_spills', ['polygon_geom'], unique=False, postgresql_using='gist')
    op.add_column('particle_trajectories', sa.Column('origin_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('particle_trajectories', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('particle_trajectories', 'spill_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('particle_trajectories', 'run_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'windage_coefficient',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'integration_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'integration_method',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=True)
    op.alter_column('particle_trajectories', 'origin_time_estimate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('particle_trajectories', 'origin_time_uncertainty_h',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('particle_trajectories', 'spatial_uncertainty_km',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('particle_trajectories', 'environmental_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('particle_trajectories', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'provenance',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_particles_spill'), table_name='particle_trajectories')
    op.create_index('idx_particle_trajectories_origin_geom', 'particle_trajectories', ['origin_geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_particle_trajectories_spill_id'), 'particle_trajectories', ['spill_id'], unique=False)
    op.add_column('satellite_images', sa.Column('footprint_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('satellite_images', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('satellite_images', 'filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('satellite_images', 'format',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('satellite_images', 'crs',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('satellite_images', 'resolution_m',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('satellite_images', 'acquisition_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('satellite_images', 'region_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('satellite_images', 'satellite_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True,
               existing_server_default=sa.text("'Sentinel-1A'"))
    op.alter_column('satellite_images', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('satellite_images', 'provenance',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('satellite_images', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('satellite_images', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index('idx_satellite_images_footprint_geom', 'satellite_images', ['footprint_geom'], unique=False, postgresql_using='gist')
    op.add_column('vessel_tracks', sa.Column('track_geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('vessel_tracks', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('vessel_tracks', 'mmsi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'spill_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('vessel_tracks', 'start_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'end_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'provenance',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index('idx_vessel_tracks_track_geom', 'vessel_tracks', ['track_geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_vessel_tracks_mmsi'), 'vessel_tracks', ['mmsi'], unique=False)
    op.alter_column('vessels', 'mmsi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('vessels', 'imo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('vessels', 'vessel_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('vessels', 'vessel_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('vessels', 'call_sign',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('vessels', 'flag',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('vessels', 'length_m',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vessels', 'beam_m',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vessels', 'draught_m',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vessels', 'gross_tonnage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('vessels', 'data_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('vessels', 'provenance',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('vessels', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vessels', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vessels', 'provenance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vessels', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vessels', 'gross_tonnage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('vessels', 'draught_m',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('vessels', 'beam_m',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('vessels', 'length_m',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('vessels', 'flag',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vessels', 'call_sign',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vessels', 'vessel_type',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vessels', 'vessel_name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vessels', 'imo',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vessels', 'mmsi',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_vessel_tracks_mmsi'), table_name='vessel_tracks')
    op.drop_index('idx_vessel_tracks_track_geom', table_name='vessel_tracks', postgresql_using='gist')
    op.alter_column('vessel_tracks', 'provenance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'end_time',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'start_time',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'spill_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vessel_tracks', 'mmsi',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vessel_tracks', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('vessel_tracks', 'track_geom')
    op.drop_index('idx_satellite_images_footprint_geom', table_name='satellite_images', postgresql_using='gist')
    op.alter_column('satellite_images', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('satellite_images', 'source',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('satellite_images', 'provenance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('satellite_images', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('satellite_images', 'satellite_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Sentinel-1A'"))
    op.alter_column('satellite_images', 'region_name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('satellite_images', 'acquisition_time',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('satellite_images', 'resolution_m',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('satellite_images', 'crs',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('satellite_images', 'format',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('satellite_images', 'filename',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('satellite_images', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('satellite_images', 'footprint_geom')
    op.drop_index(op.f('ix_particle_trajectories_spill_id'), table_name='particle_trajectories')
    op.drop_index('idx_particle_trajectories_origin_geom', table_name='particle_trajectories', postgresql_using='gist')
    op.create_index(op.f('idx_particles_spill'), 'particle_trajectories', ['spill_id', 'run_type'], unique=False)
    op.alter_column('particle_trajectories', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'provenance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'environmental_source',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('particle_trajectories', 'spatial_uncertainty_km',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('particle_trajectories', 'origin_time_uncertainty_h',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('particle_trajectories', 'origin_time_estimate',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('particle_trajectories', 'integration_method',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('particle_trajectories', 'integration_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'windage_coefficient',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'run_type',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('particle_trajectories', 'spill_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('particle_trajectories', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('particle_trajectories', 'origin_geom')
    op.drop_index('idx_oil_spills_polygon_geom', table_name='oil_spills', postgresql_using='gist')
    op.drop_index('idx_oil_spills_centroid_geom', table_name='oil_spills', postgresql_using='gist')
    op.alter_column('oil_spills', 'updated_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oil_spills', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oil_spills', 'severity',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'region_name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'model_threshold',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'preprocessing_version',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'model_version',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'provenance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oil_spills', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oil_spills', 'satellite_acquisition_time',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'detection_time',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'compactness',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'orientation_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'width_km',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'length_km',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'perimeter_km',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'area_km2',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'detection_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'detected_class',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'status',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oil_spills', 'incident_name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'satellite_image_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oil_spills', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('oil_spills', 'centroid_geom')
    op.drop_column('oil_spills', 'polygon_geom')
    op.alter_column('investigation_reports', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('investigation_reports', 'generated_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('investigation_reports', 'report_pdf_path',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('investigation_reports', 'status',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('investigation_reports', 'report_version',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('investigation_reports', 'spill_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('investigation_reports', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('environmental_fields', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'provenance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'resolution_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'source_version',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'source',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'valid_time_end',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'valid_time_start',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'field_type',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('environmental_fields', 'spill_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('environmental_fields', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_log', 'event_type',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_log', 'analysis_run_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_log', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_attributions_spill_id'), table_name='attributions')
    op.create_index(op.f('idx_attr_spill'), 'attributions', ['spill_id'], unique=False)
    op.alter_column('attributions', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('attributions', 'provenance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('attributions', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('attributions', 'temporal_window_h',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'spatial_radius_km',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'ais_coverage_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'ais_gap_duration_min',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'final_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'data_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'evidence_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_continuity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_heading',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_trajectory',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_temporal',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'weight_proximity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_continuity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_heading',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_trajectory',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_temporal',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'norm_proximity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'ais_continuity_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'heading_compat_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'track_overlap_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'time_delta_h',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'distance_km',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('attributions', 'mmsi',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('attributions', 'spill_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('attributions', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('analysis_runs', 'report_version',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'1.0'"))
    op.alter_column('analysis_runs', 'completed_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'started_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('analysis_runs', 'ais_coverage_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'ais_source',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'forecast_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'hindcast_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'windage_coefficient',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'environment_time_range_end',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'environment_time_range_start',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'environment_source',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'model_threshold',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'preprocessing_version',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'model_version',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'capture_timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'satellite_source',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'satellite_scene_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('analysis_runs', 'status',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('analysis_runs', 'run_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('analysis_runs', 'spill_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ais_observations', type_='foreignkey')
    op.drop_index(op.f('ix_ais_observations_timestamp'), table_name='ais_observations')
    op.drop_index(op.f('ix_ais_observations_mmsi'), table_name='ais_observations')
    op.drop_index('idx_ais_observations_location_geom', table_name='ais_observations', postgresql_using='gist')
    op.create_index(op.f('idx_ais_mmsi'), 'ais_observations', ['mmsi', 'timestamp'], unique=False)
    op.alter_column('ais_observations', 'source',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ais_observations', 'provenance',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ais_observations', 'data_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ais_observations', 'nav_status',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ais_observations', 'heading_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ais_observations', 'cog_deg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ais_observations', 'sog_knots',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ais_observations', 'longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ais_observations', 'latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ais_observations', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ais_observations', 'mmsi',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ais_observations', 'id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('ais_observations', 'location_geom')
    op.drop_table('alerts')
    # ### end Alembic commands ###
